#!/usr/bin/env python3
"""Figure 2A — SMT3-promoter DNA logos: SpeciesLM vs Shorkie LM vs Shorkie 15% iterative.

Published 2A stacks three conservation-weighted DNA letter logos of the SMT3 (YDR510W)
promoter, **all registered to the same 110 bp window** `SMT3_seq[690:800]`, so the motifs
**poly(dA:dT)**, **Cbf1p**, **Tye7.1** line up vertically across the three rows:

  SpeciesLM        — external `johahi/specieslm-fungi-upstream-k1` (Tomaz da Silva et al.);
                     per-position reconstruction PWM over the 1003 bp SMT3 upstream,
                     regenerated by `scripts/04_analysis/shorkie_lm/lm_SMT3_viz/
                     0_compute_specieslm_smt3.py` -> `all_prbs_SMT3.npy`, plotted [690:800].
  Shorkie LM       — SMT3 (YDR510W) gene-averaged 512 bp-upstream x_pred PWM from
                     preds_smt3_unmasked.npz, slice [201:311] (== SMT3_seq[690:800]).
  Shorkie 15% it.  — same averaging on this recheck's GPU iterative reconstruction
                     (reproduced/iterative_smt3/preds_smt3_iterative.npz), slice [201:311].

Region note: the published window is `SMT3_seq[690:800]` (matches the authors' dep_map[690:800]
zoom and 4_viz_smt3_logo_unmasked.py's [203:311]); SMT3_seq[690] == Shorkie-upstream[201]
(string-verified). The old reproduction plotted the WRONG locus (the cached `all_prbs.npy` is a
chrX:607,855-608,355 example) at the wrong width — fixed here.

Logo method (verbatim from the upstream lm_SMT3_viz scripts): conservation = 2 - entropy;
per-position letter heights = p*conservation; colours A=green, C=blue, G=orange, T=red.

Outputs reproduced/Figure_2A_reproduced.png + recheck/fig2A_consistency.csv.
Run (env yeast_ml): python reproduction/figure_02/recheck/build_2A_logos.py
"""
from __future__ import annotations
from pathlib import Path
import re
import csv

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.text import TextPath
from matplotlib.patches import PathPatch
from matplotlib.font_manager import FontProperties

from shorkie import config

WORK = str(config.path("work_root"))
F2 = Path(config.repo_root()) / "reproduction" / "figure_02"
RD = F2 / "reproduced"
RECHECK = F2 / "recheck"
RECHECK.mkdir(parents=True, exist_ok=True)

ATG = 1469400          # SMT3 (YDR510W) start codon, + strand
PAD = 512              # upstream pad (2_viz / 4_viz)
SMT3_WINDOWS_START = [1454592, 1458688, 1462784, 1466880]   # window starts (4_viz / 5_verify)

# Published 110 bp window: SMT3_seq[690:800]; Shorkie upstream slice [201:311] (SEQ[690]==up[201]).
SPEC_S, SPEC_E = 690, 800
SHO_S, SHO_E = 201, 311

ALPH = ["A", "C", "G", "T"]
_FP = FontProperties(family="DejaVu Sans", weight="bold")
_LET = {c: TextPath((-0.35, 0), c, size=1, prop=_FP) for c in "ACGT"}
_COL = {"A": "green", "C": "blue", "G": "orange", "T": "red"}  # exact published scheme


def dna_letter_at(letter, x, y, yscale, ax):
    t = (mpl.transforms.Affine2D().scale(1.35, yscale * 1.35)
         + mpl.transforms.Affine2D().translate(x, y) + ax.transData)
    ax.add_artist(PathPatch(_LET[letter], lw=0, fc=_COL[letter], transform=t))


def plot_dna_logo(ax, pwm, plot_start, plot_end):
    """Conservation-weighted letter logo (verbatim from the lm_SMT3_viz scripts)."""
    pwm = np.copy(pwm[plot_start:plot_end, :]).astype(float) + 1e-4
    pwm /= pwm.sum(axis=1, keepdims=True)
    ent = np.zeros_like(pwm)
    ent[pwm > 0] = pwm[pwm > 0] * -np.log2(pwm[pwm > 0])
    cons = 2.0 - ent.sum(axis=1)
    for j in range(pwm.shape[0]):
        order = np.argsort(pwm[j])
        for ii in range(4):
            i = order[ii]
            h = pwm[j, i] * cons[j]
            y = 0.0 if ii == 0 else float(np.sum(pwm[j, order[:ii]] * cons[j]))
            dna_letter_at(ALPH[i], j + 0.5, y, h, ax)
    ax.set_xlim(0, plot_end - plot_start)
    ax.set_ylim(0, 2)
    ax.axhline(0.01, color="black", lw=1.5)
    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)


def upstream_pwm(x):
    """Gene-averaged 512 bp-upstream PWM over the 4 SMT3 windows (+ strand)."""
    acc = np.zeros((PAD, 4)); n = 0
    for w, ws in enumerate(SMT3_WINDOWS_START):
        off = ATG - ws                       # rel_start of ATG within window w
        if off < PAD or off > x.shape[1]:
            continue
        acc += np.asarray(x[w, off - PAD:off, :], float); n += 1
    return acc / max(n, 1), n


def seq_of(pwm):
    return "".join(ALPH[i] for i in np.asarray(pwm).argmax(1))


def find_motifs(true_seq_window):
    """Locate the published motifs within the aligned 110 bp true sequence (rel positions).

    poly(dA:dT) = longest A/T run; Cbf1p = CACGTG E-box; Tye7.1 = the next CANNTG E-box.
    Returns list of (center_rel_x, label).
    """
    seq = true_seq_window
    out = []
    runs = list(re.finditer("A{6,}|T{6,}", seq))
    if runs:
        r = max(runs, key=lambda m: m.end() - m.start())
        out.append((0.5 * (r.start() + r.end()), "Poly(dA:dt)"))
    ebx = [m.start() for m in re.finditer("CACGTG", seq)]
    if ebx:
        out.append((ebx[0] + 3, "Cbf1p"))
    # Tye7.1 = first CANNTG E-box downstream of Cbf1p (true seq has CATGTG; model renders the E-box)
    cann = [m.start() for m in re.finditer("CA[ACGT][ACGT]TG", seq)]
    tye = [p for p in cann if not ebx or p > ebx[0] + 1]
    if tye:
        out.append((tye[0] + 3, "Tye7.1"))
    return out


def load_specieslm():
    """Regenerated SpeciesLM SMT3 reconstruction PWM (1003,4)."""
    for p in [RD / "specieslm_smt3" / "all_prbs_SMT3.npy",
              Path(WORK) / "experiments" / "dependencies_DNALM" / "all_prbs_SMT3.npy"]:
        if p.is_file():
            ap = np.load(p).astype(float)
            if ap.shape[0] >= SPEC_E:
                return ap, str(p)
    raise FileNotFoundError(
        "all_prbs_SMT3.npy not found — run scripts/04_analysis/shorkie_lm/lm_SMT3_viz/"
        "0_compute_specieslm_smt3.py (env pytorch_cuda) first.")


def main():
    # --- data ---
    spec, spec_path = load_specieslm()
    uz = np.load(f"{WORK}/experiments/Shorkie_LM_SMT3_viz/inference_smt3_output/preds_smt3_unmasked.npz")
    sho_up, n_un = upstream_pwm(np.asarray(uz["x_pred"], float))
    true_up, _ = upstream_pwm(np.asarray(uz["x_true"], float))
    iz = np.load(RD / "iterative_smt3" / "preds_smt3_iterative.npz", allow_pickle=True)
    sho_iter_up, _ = upstream_pwm(np.asarray(iz["x_pred_iter"], float))

    # alignment self-check: the three rows must share the same genomic frame
    true_win = seq_of(true_up[SHO_S:SHO_E])              # genome truth over the window
    spec_win = seq_of(spec[SPEC_S:SPEC_E])               # SpeciesLM argmax over the window
    spec_agree = float(np.mean([a == b for a, b in zip(spec_win, true_win)]))
    sho_agree = float(np.mean([a == b for a, b in zip(seq_of(sho_up[SHO_S:SHO_E]), true_win)]))
    width_ok = (SPEC_E - SPEC_S) == (SHO_E - SHO_S)

    # --- figure: 3 stacked rows, common 110 bp frame, motif labels on top ---
    motifs = find_motifs(true_win)
    fig, axes = plt.subplots(3, 1, figsize=(15.0, 4.6), sharex=True)
    rows = [
        (axes[0], spec, SPEC_S, SPEC_E, "SpeciesLM\n(Tomaz da Silva et al.)"),
        (axes[1], sho_up, SHO_S, SHO_E, "Shorkie LM"),
        (axes[2], sho_iter_up, SHO_S, SHO_E, "Shorkie LM\n15% iterative"),
    ]
    for ax, pwm, s, e, label in rows:
        plot_dna_logo(ax, pwm, s, e)
        ax.set_ylabel(label, rotation=0, ha="right", va="center", fontsize=10, labelpad=8)

    # motif annotations once along the top, centred over the aligned x (published style: no
    # vertical guide lines — the three rows share the x-axis so the motifs already register)
    top = axes[0]
    for cx, lab in motifs:
        top.text(cx, 2.16, lab, ha="center", va="bottom", fontsize=12, fontweight="bold", color="0.1")
    top.set_ylim(0, 2)

    fig.subplots_adjust(left=0.16, right=0.995, top=0.86, bottom=0.04, hspace=0.18)
    out = RD / "Figure_2A_reproduced.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)

    # --- consistency / alignment metrics ---
    def corr(a, b):
        a = a[SHO_S:SHO_E]; b = b[SHO_S:SHO_E]
        return float(np.corrcoef(a.ravel(), b.ravel())[0, 1])
    recon = float((sho_up[SHO_S:SHO_E].argmax(1) == true_up[SHO_S:SHO_E].argmax(1)).mean())
    # SpeciesLM vs Shorkie are different arrays but now cover the SAME genomic window:
    spec_sho_corr = float(np.corrcoef(spec[SPEC_S:SPEC_E].ravel(), sho_up[SHO_S:SHO_E].ravel())[0, 1])
    rows_csv = [
        ("region_window", "SMT3_seq[690:800] (110bp); Shorkie upstream[201:311]"),
        ("three_rows_same_width", int(width_ok)),
        ("SpeciesLM_argmax_vs_genome_agree", round(spec_agree, 4)),
        ("Shorkie_argmax_vs_genome_agree", round(sho_agree, 4)),
        ("SpeciesLM_vs_Shorkie_registered_pwm_corr", round(spec_sho_corr, 4)),
        ("Shorkie_unmasked_vs_iter_pwm_corr", round(corr(sho_up, sho_iter_up), 4)),
        ("Shorkie_unmasked_recon_acc_vs_genome", round(recon, 4)),
        ("Cbf1_Ebox(CACGTG)_in_window", int(bool(re.search("CACGTG", true_win)))),
        ("polydAdT_run>=6_in_window", int(bool(re.search("A{6,}|T{6,}", true_win)))),
    ]
    with open(RECHECK / "fig2A_consistency.csv", "w", newline="") as f:
        w = csv.writer(f); w.writerow(["metric", "value"])
        for k, v in rows_csv:
            print(f"  {k:<46} {v}"); w.writerow([k, v])
    print(f"[info] SpeciesLM PWM: {spec_path}")
    print(f"[info] motifs (rel x): {motifs}")
    print(f"[OK] -> {out}")


if __name__ == "__main__":
    main()
