#!/usr/bin/env python3
"""Figure 7 C + D (deep-recheck) — published-style schematics.

C: logSED computation cartoon — 16 bp-resolution coverage bins, Ref (blue) over Alt
   (orange), SNP star, gene-body boxes, the Cov_ref / Cov_alt = SUM-of-bins call-outs and
   the formula logSED = log2(Cov_alt + 1) - log2(Cov_ref + 1).
D: negative-control cartoon — a Positive eQTL (SNP 230 bp upstream of Gene1, blue) and a
   Negative eQTL (SNP 230 bp from Gene2, red) with the 100 bp matching tolerance.

These are schematics (no data); they mirror the published Figure 7 C/D illustrations. The
data-level evidence that the negatives are TSS-distance-matched is kept separately as the
ECDF support panel (panel_D_ecdf_support.png), regenerated by build_7D_ecdf_support().

Outputs: reproduced/Figure_7C_reproduced.png, reproduced/Figure_7D_reproduced.png
"""
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon, Rectangle, FancyArrow

from shorkie import config

config.load()
REPRO = config.repo_root() / "reproduction" / "figure_07"
BLUE = "#1f77b4"; ORANGE = "#ff7f0e"; GENEBLUE = "#1f3fd6"; RED = "#d62728"


def gene_box(ax, x0, x1, y, h, color, n_arrows=4, strand="+"):
    ax.add_patch(Rectangle((x0, y - h / 2), x1 - x0, h, fc=color, ec="none"))
    for k in range(n_arrows):
        xc = x0 + (k + 0.5) * (x1 - x0) / n_arrows
        dx = (x1 - x0) * 0.04 * (1 if strand == "+" else -1)
        ax.add_patch(Polygon([(xc - dx, y - h * 0.32), (xc + dx, y), (xc - dx, y + h * 0.32)],
                             closed=True, fc="white", ec="none"))


def build_C():
    fig, ax = plt.subplots(figsize=(8.2, 5.2))
    ax.axis("off")
    ax.set_xlim(0, 12); ax.set_ylim(-3.2, 6.2)
    ax.text(11.6, 5.9, "16bp resolution", ha="right", va="top", fontsize=12, style="italic")

    # baseline + SNP
    ax.plot([0.3, 11.6], [0, 0], color="black", lw=1.3)
    ax.plot([0.7], [0], marker="*", ms=22, color="black", clip_on=False)
    ax.text(0.7, -0.5, "SNP", ha="center", va="top", fontsize=11)

    # coverage bins: bimodal profile, Ref (blue) slightly above Alt (orange)
    xs = np.linspace(2.4, 11.2, 22)
    w = (xs[1] - xs[0]) * 0.92
    prof = (np.exp(-((xs - 4.6) ** 2) / 1.2) * 2.4 + np.exp(-((xs - 8.6) ** 2) / 2.0) * 4.8)
    ref_h = prof + 0.6
    rng = np.sin(np.arange(len(xs))) * 0.18
    alt_h = ref_h * 0.78 + rng
    for x, rh, ah in zip(xs, ref_h, alt_h):
        ax.add_patch(Rectangle((x - w / 2, 0), w, rh, fc=BLUE, ec="white", lw=0.4, alpha=0.95))
        ax.add_patch(Rectangle((x - w / 2, 0), w, max(ah, 0.05), fc=ORANGE, ec="white", lw=0.4, alpha=0.9))

    # gene-body boxes (two exons + intron arrow)
    gy = -1.4
    gene_box(ax, 2.6, 4.9, gy, 0.7, GENEBLUE, n_arrows=3)
    gene_box(ax, 5.6, 11.1, gy, 0.7, GENEBLUE, n_arrows=6)
    ax.annotate("", xy=(5.6, gy), xytext=(4.9, gy),
                arrowprops=dict(arrowstyle="->", color="black", lw=1.2))

    # SUM-of-bins call-outs
    ax.add_patch(Polygon([(2.4, -1.9), (6.6, -1.9), (4.5, -0.05)], closed=True, fc=BLUE, alpha=0.12))
    ax.add_patch(Polygon([(6.8, -1.9), (11.2, -1.9), (9.0, -0.05)], closed=True, fc=ORANGE, alpha=0.16))
    ax.text(4.4, -2.15, r"Cov$_{ref}$ = SUM of bins", ha="center", va="top", fontsize=11, color=BLUE)
    ax.text(9.0, -2.15, r"Cov$_{alt}$ = SUM of bins", ha="center", va="top", fontsize=11, color="#e07b00")

    # formula
    ax.text(6.0, -2.95,
            r"$\log\,\mathrm{SED} = \log_2(\mathrm{Cov_{alt}}+1) - \log_2(\mathrm{Cov_{ref}}+1)$",
            ha="center", va="center", fontsize=14)

    # legend
    ax.add_patch(Rectangle((10.4, 5.0), 0.4, 0.4, fc=BLUE)); ax.text(10.95, 5.2, "Ref", va="center", fontsize=10)
    ax.add_patch(Rectangle((10.4, 4.4), 0.4, 0.4, fc=ORANGE)); ax.text(10.95, 4.6, "Alt", va="center", fontsize=10)

    ax.set_title("C  logSED computation", fontsize=13, loc="left")
    fig.tight_layout()
    out = REPRO / "reproduced" / "Figure_7C_reproduced.png"
    fig.savefig(out, dpi=150); plt.close(fig)
    print("saved", out)


def build_D():
    fig, axes = plt.subplots(2, 1, figsize=(8.2, 5.0))
    for ax in axes:
        ax.axis("off"); ax.set_xlim(0, 12); ax.set_ylim(-1.4, 1.6)

    # Positive eQTL
    ax = axes[0]
    ax.text(0.1, 1.35, "Positive eQTL", fontsize=13, fontweight="bold", color=GENEBLUE)
    ax.plot([0.3, 11.7], [0, 0], color="black", lw=1.3)
    ax.plot([1.4], [0], marker="*", ms=20, color="black", clip_on=False)
    ax.text(1.4, -0.35, "SNP (Ref: A / Alt: C)", ha="center", va="top", fontsize=10)
    ax.annotate("", xy=(4.7, 0.55), xytext=(1.4, 0.55),
                arrowprops=dict(arrowstyle="<->", color="black", lw=1.1))
    ax.text(3.05, 0.75, "230 bp", ha="center", fontsize=10)
    gene_box(ax, 4.8, 6.2, 0.0, 0.55, GENEBLUE, n_arrows=2)
    gene_box(ax, 6.6, 11.2, 0.0, 0.55, GENEBLUE, n_arrows=6)
    ax.text(11.4, 0.0, "Gene1", ha="left", va="center", fontsize=12, fontweight="bold")

    # Negative eQTL
    ax = axes[1]
    ax.text(0.1, 1.35, "Negative eQTL", fontsize=13, fontweight="bold", color=RED)
    ax.plot([0.3, 11.7], [0, 0], color="black", lw=1.3)
    ax.add_patch(Rectangle((0.9, -0.18), 1.0, 0.36, fc="none", ec=RED, hatch="////", lw=1.0))
    ax.plot([1.4], [0], marker="*", ms=20, color=RED, clip_on=False)
    ax.text(1.4, -0.35, "SNP (Ref: A / Alt: C)", ha="center", va="top", fontsize=10)
    ax.annotate("", xy=(0.9, -0.7), xytext=(1.9, -0.7),
                arrowprops=dict(arrowstyle="<->", color=RED, lw=1.0))
    ax.text(1.4, -0.95, "100 bp tolerance", ha="center", va="top", fontsize=9, color=RED)
    ax.annotate("", xy=(4.7, 0.55), xytext=(1.4, 0.55),
                arrowprops=dict(arrowstyle="<->", color="black", lw=1.1))
    ax.text(3.05, 0.75, "230 bp", ha="center", fontsize=10)
    gene_box(ax, 4.8, 11.2, 0.0, 0.55, RED, n_arrows=8)
    ax.text(11.4, 0.0, "Gene2", ha="left", va="center", fontsize=12, fontweight="bold")

    fig.suptitle("D  matched negative-control generation", fontsize=13, x=0.12, ha="left")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    out = REPRO / "reproduced" / "Figure_7D_reproduced.png"
    fig.savefig(out, dpi=150); plt.close(fig)
    print("saved", out)


def main():
    build_C()
    build_D()


if __name__ == "__main__":
    main()
